version: 2
updates:
  - package-ecosystem: "terraform"
    directory: "/terraform/cluster-config"
    schedule:
      interval: "daily"
  - package-ecosystem: "terraform"
    directory: "/terraform/cluster-infra"
    schedule:
      interval: "daily"
