config:
  issuer: https://login.ugo-k8s.adorsys-sandbox.aws.adorsys.de/dex/

  # The storage configuration determines where dex stores its state. Supported
  # options include SQL flavors and Kubernetes third party resources.
  #
  # See the documentation (https://dexidp.io/docs/storage/) for further information.
  storage:
    type: kubernetes
    config:
      inCluster: true

  # Configuration for the HTTP endpoints.
  web:
    http: 0.0.0.0:5556
    #tlsCert: /etc/dex/localhost.crt
    #tlsKey: /etc/dex/localhost.key
  # Configuration for telemetry
  telemetry:
    http: 0.0.0.0:5558

  # Instead of reading from an external storage, use this list of clients.
  #
  # If this option isn't chosen clients may be added through the gRPC API.
  staticClients:
  - id: kubernetes
    redirectURIs:
    name: 'Example App'
    secret: ZXhhbXBsZS1hcHAtc2Vjaaa
    redirectURIs:
    - http://127.0.0.1:5555/callback
    - http://localhost:8000
    - http://localhost:18000
  - IDEnv: client-id
    redirectURIs:
    -  https://argo.ugo-k8s.adorsys-sandbox.aws.adorsys.de/auth/callback
    name: 'Argocd'
    secretEnv: client-secret
  connectors:
  - type: github
    # Required field for connector id.
    id: github
    # Required field for connector name.
    name: GitHub
    config:
      # Credentials can be string literals or pulled from the environment.
      clientID: $GITHUB_CLIENT_ID
      clientSecret: $GITHUB_CLIENT_SECRET
      redirectURI: https://login.ugo-k8s.adorsys-sandbox.aws.adorsys.de/dex/callback
      orgs:
      - name: nce-acme
        # A white list of teams. Only include group claims for these teams.
        teams:
        - admin
        - zuschauer
      # Flag which indicates that all user groups and teams should be loaded.
      loadAllGroups: false
  # - type: google
  #   id: google
  #   name: Google
  #   config:
  #     issuer: https://accounts.google.com
  #     # Connector config values starting with a "$" will read from the environment.
  #     clientID: $GOOGLE_CLIENT_ID
  #     clientSecret: $GOOGLE_CLIENT_SECRET
  #     redirectURI: http://127.0.0.1:5556/dex/callback
  #     hostedDomains:
  #     - $GOOGLE_HOSTED_DOMAIN

  # Let dex keep a list of passwords which can be used to login to dex.
  enablePasswordDB: false

